[project]
name = "obtencion-almacenamiento-datos"
version = "0.1.0"
description = "Archivo de dependencias necesarias para el proyecto"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymeteosource>=1.7.0",
    "pymongo>=4.15.4",
]
